# Generated by Django 3.1.7 on 2023-11-07 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0004_auto_20231107_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(limit_choices_to={'district': True}, on_delete=django.db.models.deletion.CASCADE, to='bank_app.branch'),
        ),
    ]
