# Generated by Django 3.1.7 on 2023-11-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0012_auto_20231108_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='materials_provided',
        ),
        migrations.AddField(
            model_name='customer',
            name='materials_provided',
            field=models.ManyToManyField(to='bank_app.Material'),
        ),
    ]
