# Generated by Django 3.1.7 on 2023-11-08 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_app', '0013_auto_20231108_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_type',
            field=models.CharField(choices=[('Savings', 'Savings Account'), ('Current', 'Current Account')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='branch',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='district', chained_model_field='district', on_delete=django.db.models.deletion.CASCADE, to='bank_app.branch'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='materials_provided',
        ),
        migrations.AddField(
            model_name='customer',
            name='materials_provided',
            field=models.CharField(choices=[('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card'), ('Cheque Book', 'Cheque Book')], default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
