# Generated by Django 3.1.7 on 2023-11-08 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0016_auto_20231108_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
