# Generated by Django 3.1.7 on 2023-11-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0018_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='materials_provided',
            field=models.BooleanField(choices=[('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card'), ('Cheque Book', 'Cheque Book')], default='your card', max_length=250),
        ),
    ]
