# Generated by Django 3.1.7 on 2023-11-10 05:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0020_auto_20231108_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='materials_provided',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card'), ('Cheque Book', 'Cheque Book')], default='your card', max_length=34),
        ),
    ]
